/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        menu();
    }

    // menu pilihan
    public static void menu(){

        Scanner scan = new Scanner(System.in);
        System.out.println("pilih menu : ");
        System.out.println("1 : menghitung rata-rata bilangan : ");
        System.out.println("2 : menghitung luas lingkaran : ");
        System.out.print("pilih : ");
        int pilihan = scan.nextInt();
        if (pilihan == 1){
            Rata.RataRataEmpatBilangan(scan);
        } else if (pilihan == 2){
            HitungLingkaran.HitungLuasLingkaran(scan);
        }
        System.out.println("\n\n\n\n\n\n");
        menu();
    }
}
